spring:
  application:
    name: platform
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# 日志配置（通用）
logging:
  include-application-name: false
  level:
    root: INFO
  file:
    name: logs/platform.log
  logback:
    rolling-policy:
      max-file-size: 10MB
      max-history: 30

# MyBatis-Plus 配置（通用）
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.bryan.platform.domain.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1

# 第三方 API 配置（通用）
deepseek:
  api:
    key: "${DEEPSEEK_API_KEY}" # Set your own api key as environment variable
    url: "https://api.deepseek.com/chat/completions"
    model: "deepseek-chat"